trackawesomelist/trackawesomelist-source

config.yml

Added GPT 3 and ChatGPT Awesome repos

Added GPT 3 and ChatGPT Awesome repos

---

config.yml

Added Polars Awesome repo

---

config.yml

Adds https://github.com/beansource/awesome-orgs to Miscellaneous 😎

chore: add awesome-orgs

---

config.yml

Should fix https://github.com/trackawesomelist/trackawesomelist/issues/6

Fix ipfs/awesome-ipfs

---

config.yml

Add awesome GitHub Wiki https://github.com/MyHoneyBadger/awesome-github-wiki#readme

Add awesome GitHub Wiki

---

config.yml

Added ai-collective-tools in config.yml

feat: 🎨: added aicollective.tools in config.yml

---

config.yml

Add [Awesome Kustomize](https://github.com/aabouzaid/awesome-kustomize/) list.

Add Awesome Kustomize list

---

config.yml

Hi
I want to add asdf plugin repo, which contain list of asdf plugin. Asdf is Multiple Runtime Version Manager. Asdf plugin can be use with rtx.

add asdf plugin repo

---

config.yml

**awesome-ai4lam** is a curated list of resources, projects, and tools for using Artificial Intelligence in Libraries, Archives, and Museums (LAM).
In adding an entry for this awesome list, I struggled with finding an appropriate category, and finally decided it would be best to propose a new category. This will allow other related awesome lists to be put under it. However, if this is not the right way to propose new categories or else this category doesn't seem like a good choice, I'd be happy to revise the PR if I could get some guidance about what to do.

Add entry for awesome-ai4lam

---

config.yml

Add QGis awesome list

---

.editorconfig
config.yml

EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs.
Remove trailing whitespace in `config.yml` and avoid future recurrence with `.editorconfig`.

style: add editorconfig file with config.yml styling

---

config.yml

Hey thanks for the website tracking all the `awesome-*` repos!

feat: add awesome-glp1 listing

---

config.yml

@theowenyoung It seems #24 broke the [cronjob](https://github.com/trackawesomelist/trackawesomelist-source/actions/runs/8048925374/job/21981276215#step:9:1998).
```
INFO cloning https://github.com/glp1guide/awesome-glp1.git to /home/runner/work/trackawesomelist-source/trackawesomelist-source/cache/repos/glp1guide/awesome-glp1
Cloning into '/home/runner/work/trackawesomelist-source/trackawesomelist-source/cache/repos/glp1guide/awesome-glp1'...
fatal: no such path 'readme.md' in HEAD
```
Close #27 :crossed_fingers:

Change README filename for awesome-glp1

---

config.yml

Add this:
https://github.com/stan8086/awesome-distraction-blocker

Add Awesome Distraction Blocker

---

config.yml

Add this list:
https://github.com/dariubs/awesome-workflow-automation

Add Awesome Workflow Automation

---

config.yml

Hello,
please consider adding this project: http://github.com/nikolaydubina/go-recipes
I have been featured in major Golang community channels, newsletters, and was trending in GitHub Explore multiple times.
Thank you!

added-go-recipes

---

config.yml

Thank you so much for this prtoject! 
I would like to add [capawesome-team/awesome-capacitorjs](https://github.com/capawesome-team/awesome-capacitorjs) to your list.

Add `capawesome-team/awesome-capacitorjs` to `config.yml`

---

config.yml

Add this list:
https://github.com/mga-mirth/awesome-mirth

add awesome Mirth

---

config.yml

Add [Awesome Marketing](https://github.com/marketingtoolslist/awesome-marketing)

Add Awesome Marketing

---

config.yml

Hello, 
please add the repo lightszentip/awesome-laravel-filament for list of good packages to develop a filament & laravel application.
Thanks.

feat: add lightszentip/awesome-laravel-filament

---

config.yml

Added Firebase genkit awesome list

feat: Added Firebase genkit awesome list

---

config.yml

Added Awesome Windows to the `config.yml`

Add Awesome Windows

---

config.yml

The repo is returning a 404, and it is causing the cron task to fail continuously, and the database not be rebuilt.

config: comment out `shime/creative-commons-media`
